### ISSUE TITLE
About copy change

### ISSUE THREAD

**Issue by rsamai** [Camp-PolyHacks/polyhacks.io#42]
"Over two days, Cal Poly students of all backgrounds work in teams to ideate, design, pitch, and market their solution to a problem facing our San Luis Obispo community. It’s a Learn by Doing marathon of collaboration, learning, and creativity."

//The trails actually don't relate to SLO this year, and I feel like this might mislead campers to think it's like last year, ya know? 
change to 
"Over two days, Cal Poly students of all backgrounds work in teams to ideate, design, pitch, and market their solution to a problem facing the community. It’s a Learn by Doing marathon of collaboration, learning, and creativity."

**Comment by javag97** [comment]
I agree. Changed!
