### ISSUE TITLE
How do I form teams, and how big can each team be? edit

### ISSUE THREAD

**Issue by rsamai** [Camp-PolyHacks/polyhacks.io#44]
Change "Teams can be up to 10 people. If you don’t have a team yet, that’s okay! There will be time to ﬁnd one on Friday before the hacking begins." to 
"Teams can be up to 8 people and must have at least 1 hustler, hacker, and hipster. If you don’t have a team yet, that’s okay! There will be time to ﬁnd one on Friday before the hacking begins."

**Comment by javag97** [comment]
Done.  Pushing in a second.
