### ISSUE TITLE
Move Full Schedule button

### ISSUE THREAD

**Issue by rsamai** [Camp-PolyHacks/polyhacks.io#63]
It's a little hidden right now and I'm afraid users might not catch it. Can you please move the button to right under the Schedule header?

**Comment by javag97** [comment]
@dhahn9 whatchu think?

**Comment by dhahn9** [comment]
@javag97 I think we should move it where Rutu suggested for now. I could see it going on landing page too tbh, @rsamai what do you think about this?

**Comment by rsamai** [comment]
Mm I think 3 buttons on the landing page is too much and campers can click on the schedule tab in the nav bar!

**Comment by dhahn9** [comment]
okay! then @javag97, lets go with what Rutu first suggested.
